---
- name:               Create VPC
  ec2_vpc_net:
    name:             "{{ vpc_name }}"
    cidr_block:       "{{ vpc_cidr_block }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    state:            "present"
  register: vpc
  tags: create-ms-ad

- name:               Create Public Subnet
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc.vpc.id }}"
    cidr:             "{{ public_subnet_cidr }}"
    az:               "{{ aws_region }}a"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    resource_tags:
      Name:           "Public Subnet"
  register: public_subnet
  tags: create-ms-ad

- name:               Create Private Subnet
  ec2_vpc_subnet:
    state:            "present"
    vpc_id:           "{{ vpc.vpc.id }}"
    cidr:             "{{ private_subnet_cidr }}"
    az:               "{{ aws_region }}b"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    resource_tags:
      Name:           "Private Subnet"
  register: private_subnet
  tags: create-ms-ad

- name:               Create Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id:           "{{ vpc.vpc.id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    state:            "present"
  register: vpc_igw

- name:               Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id:           "{{ vpc.vpc.id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    tags:
      Name:           "Public"
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest:         "0.0.0.0/0"
        gateway_id:   "{{ vpc_igw.gateway_id }}"

- name:               Create Public Security Group
  ec2_group:
    name:             "{{ public_security_group_name }}"
    description:      "Evojam Security Group"
    vpc_id:           "{{ vpc.vpc.id }}"
    region:           "{{ aws_region }}"
    aws_access_key:   "{{ aws_access_key }}"
    aws_secret_key:   "{{ aws_secret_key }}"
    rules:
      - proto:        "tcp"
        from_port:    "1"
        to_port:      "65535"
        cidr_ip:      "{{ trusted_net }}"
  register: public_group

